apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oficina

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

# A pipeline substitui a imagem: kustomize edit set image oficina-api=<ECR>:<sha>
images:
  - name: oficina-api
    newName: oficina-api
    newTag: latest
