apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oficina-api
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: oficina-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
